op  |*> #=> merge-labels(|op: > + |_self>)
op1 |*> #=> merge-labels(|op1: > + |_self>)
op2 |*> #=> merge-labels(|op2: > + |_self>)
op3 |*> #=> merge-labels(|op3: > + |_self>)
op4 |*> #=> merge-labels(|op4: > + |_self>)
op5 |*> #=> merge-labels(|op5: > + |_self>)
op6 |*> #=> merge-labels(|op6: > + |_self>)
op7 |*> #=> merge-labels(|op7: > + |_self>)
op8 |*> #=> merge-labels(|op8: > + |_self>)
op9 |*> #=> merge-labels(|op9: > + |_self>)

sp  |*> #=> merge-labels(|sp: > + |_self>)
