|person: Fred Smith> => |word: fred> + |word: freddie> + |word: simth> + |word: smithie>
|person: Mary> => |word: mazza>
|greeting: Hey!> => |word: hey>
|question: what is> => |word: what's>
|direction: up> => |word: up>
|phrase: having a baby> => read |text: having a baby>
|phrase: in the family way> => read |text: in the family way>
|phrase: up the duff> => read |text: up the duff>
|phrase: with child> => read |text: with child>
|concept: pregnancy> => |phrase: having a baby> + |phrase: in the family way> + |phrase: up the duff> + |phrase: with child>
